[programs.localnet]
anchor_escrow = "4Hv8isR2b4ha1nsMceSuGT5sc4eto4sPLXHf8Q791dJz"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/kien6034/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
